# For more information: https://laravel.com/docs/sail
version: '3.8'
services:
    order:
        env_file:
            - apps/order/.env
        build:
            context: apps/order/vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${ORDER_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - './apps/order:/var/www/html'
        depends_on:
            - rabbitmq
        networks:
            - adr

    product:
        env_file:
            - apps/product/.env
        build:
            context: apps/product/vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${PRODUCT_PORT}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - './apps/product:/var/www/html'
        depends_on:
            - rabbitmq
        networks:
            - adr

    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbitmq'
        ports:
            - '5672:5672'
            - '15672:15672'
        volumes:
            - '~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/'
            - '~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq'
            - './apps/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro'
            - './apps/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro'
        networks:
            - adr

networks:
    adr:
        driver: bridge
